name: Cypress Testing

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: remove package-lock.json
        working-directory: client
        run: rm package-lock.json
      - name: install packages
        working-directory: client
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          working-directory: client

          

      
          
 
