name: Cypress Testing

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: npm start
          working-directory: client
          

      
          
 
